export const GET_ERRORS = 'GET_ERRORS';
export const NO_ERRORS = 'NO_ERRORS';

// authentication
export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES';
export const REGISTER_COMPANY_FAIL = 'REGISTER_COMPANY_FAIL';
export const REGISTER_COMPANY_SUCCESS = 'REGISTER_COMPANY_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_DEFAULT = 'LOGIN_DEFAULT'
export const CREATE_DIETICIAN_SUCCESS = 'CREATE_DIETICIAN_SUCCESS';
export const CREATE_DIETICIAN_FAIL = 'CREATE_DIETICIAN_SUCCESS';
export const CREATE_DIETICIAN_DEFAULT = 'CREATE_DIETICIAN_DEFAULT';
export const CREATE_PATIENT_SUCCESS = 'CREATE_PATIENT_SUCCESS';
export const CREATE_PATIENT_FAIL = 'CREATE_PATIENT_FAIL';

export const UPDATE_COMPANY_DATA = 'UPDATE_COMPANY_DATA';
export const GET_ALL_ADMINS = 'GET_ALL_ADMINS';
export const DELETE_USER = 'DELETE_USER';

//patients
export const GET_ALL_PATIENTS = 'GET_ALL_PATIENTS';
export const EDIT_PATIENT = 'EDIT_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT';
export const GET_PATIENT_BY_ID = 'GET_PATIENT_BY_ID';
export const PATIENT_GET_DIETITIAN_BY_ID = 'PATIENT_GET_DIETITIAN_BY_ID';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';

export const DOC_CONTENT_URL = 'DOC_CONTENT_URL';

// dietitian
export const GET_ALL_DIETICIANS = 'GET_ALL_DIETICIANS';
export const GET_DIETITIAN = 'GET_DIETITIAN';
export const UPDATE_DIETITIAN_DATA = 'UPDATE_DIETITIAN_DATA';
export const GET_DIETITIAN_BY_ID = 'GET_DIETITIAN_BY_ID';
export const GET_DOCUMENTS = 'GET_DOCUMENTS';

// appointments 
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';


// formbuilder
export const ADD_FORM_ITEM = 'ADD_FORM_ITEM';
export const REMOVE_FORM_ITEM = 'REMOVE_FORM_ITEM';
export const REMOVE_ITEM_OPTION = 'REMOVE_ITEM_OPTION';
export const ADD_ITEM_OPTION = 'ADD_ITEM_OPTION';
export const SET_FIELD_TITLE = 'SET_FIELD_TITLE';
export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
export const CREATE_INTAKE_FORM = 'CREATE_INTAKE_FORM';
export const SET_REQUIRED = 'SET_REQUIRED';
export const GET_INTAKE_FORMS = 'GET_INTAKE_FORMS';

export const CREATE_INTAKE_INFO = 'CREATE_INTAKE_INFO';
export const GET_INTAKE_INFOS = 'GET_INTAKE_INFOS';

// appointment
export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';